# Generated by Django 3.1.3 on 2021-10-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
